version: '3.9'
services:
  php-env:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db
  composer:
    image: composer:2.7.1
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  php:
    restart: "no"
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    restart: "no"
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  phpstan:
    restart: "no"
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpstan
  phpcs:
    restart: "no"
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpcs
